### ISSUE TITLE
_caffe.so missing

### ISSUE THREAD

**Issue by jlyw1017** [yangguorun/SegStereo#4]
### Issue summary
Hey
Thank you for your work!
The problem is, I noticed you have used the caffe under SegSetero under python  in get_disp.py
sys.path.insert(0, caffe_root+'python')
but There isn't the _caffe.so file so there would be a error.

  File "../python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "../python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe
I think it is trying to import caffe under SegStere/python but there isn't the _caffe.so file

If I use my own caffe in my system there would be a  error like :
[libprotobuf ERROR /home/jlyw1017/catkin_ws/protobuf/src/google/protobuf/text_format.cc:288] Error parsing text-format caffe.NetParameter: 50:12: Message type "caffe.LayerParameter" has no field named "bn_param".
could upload your _caffe under caffe python?
oder do you know any work around?
Thank you!

### System configuration

* Operating system: 
* Compiler: 
* CUDA version (9.0): 
* CUDNN version (if applicable): 
* BLAS: 
* Python version (2.7):

**Comment by jlyw1017** [comment]
Eh. found that I  just need to build the caffe her again.
close it

**Comment by jlyw1017** [comment]
Eh. found that I just need to build the caffe her again.
close it

**Comment by fenil25** [comment]
Can you tell me exactly how you solved this? I am facing the same issue.
